import { useEffect, useMemo, useState } from 'react';
import * as echarts from 'echarts';
import type { Cache, Metadata, SpecialMetric } from '../core/domain';
import './dashboard.css';

function Chart({ options }: { options: echarts.EChartsOption }) {
  const ref = useMemo(() => ({ current: null as HTMLDivElement | null }), []);
  useEffect(() => { if (!ref.current) return; const chart = echarts.init(ref.current); chart.setOption(options); return () => chart.dispose(); }, [options, ref]);
  return <div className="chart" ref={(node) => { ref.current = node; }} />;
}

const numberLabel = (number: number) => String(number).padStart(2, '0');
const days = (value: number) => Number.isFinite(value) ? `${value.toFixed(1)} ngày` : 'Chưa xuất hiện';
const specialChart = (items: SpecialMetric[]): echarts.EChartsOption => ({ backgroundColor: 'transparent', tooltip: { trigger: 'axis' }, legend: { data: ['Số lần xuất hiện', 'Ngày từ lần gần nhất'] }, xAxis: { type: 'category', data: items.map((item) => numberLabel(item.number)) }, yAxis: [{ type: 'value', name: 'Lần' }, { type: 'value', name: 'Ngày' }], series: [{ name: 'Số lần xuất hiện', type: 'bar', data: items.map((item) => item.count), itemStyle: { color: '#fb923c' } }, { name: 'Ngày từ lần gần nhất', type: 'line', yAxisIndex: 1, data: items.map((item) => Number(item.daysSinceLatest.toFixed(1))), smooth: true, itemStyle: { color: '#60a5fa' } }] });
const associationChart = (special: number, values: { number: number; count: number }[]): echarts.EChartsOption => ({ backgroundColor: 'transparent', tooltip: { trigger: 'axis' }, xAxis: { type: 'category', data: values.map((item) => numberLabel(item.number)) }, yAxis: { type: 'value', name: 'Lần đi cùng' }, series: [{ name: `Số xanh đi cùng ĐB ${numberLabel(special)}`, type: 'bar', data: values.map((item) => item.count), itemStyle: { color: '#22c55e' } }] });

export default function App() {
  const [payload, setPayload] = useState<{ metadata: Metadata; cache: Cache; sourceStatus?: 'live' | 'fallback'; checkedAt?: string } | null>(null); const [dark, setDark] = useState(true); const [selectedSpecial, setSelectedSpecial] = useState(1);
  useEffect(() => { fetch('/api/dashboard', { cache: 'no-store' }).then((response) => { if (!response.ok) throw new Error('Dynamic endpoint unavailable'); return response.json() as Promise<{ cache: Cache; metadata: Metadata; sourceStatus: 'live' | 'fallback'; checkedAt: string }>; }).then(setPayload).catch(() => fetch('/data/cache.json').then((response) => response.json()).then((cache: Cache) => fetch('/data/metadata.json').then((response) => response.json()).then((metadata: Metadata) => setPayload({ cache, metadata, sourceStatus: 'fallback' })))); }, []);
  if (!payload) return <main><h1>Historical Event Analysis</h1><p>Không thể đọc cache dữ liệu.</p></main>;
  const { metadata, cache } = payload; const special = cache.statistics.specialFrequency ?? []; const associations = cache.statistics.specialAssociations?.[String(selectedSpecial)] ?? []; const transitions = cache.statistics.specialTransitions?.[String(selectedSpecial)] ?? []; const current = special.find((item) => item.number === selectedSpecial); const overdue = [...special].filter((item) => Number.isFinite(item.overdueDays)).sort((a, b) => b.overdueDays - a.overdueDays).slice(0, 3); const backtest = cache.statistics.specialBacktest; const at13 = cache.statistics.specialByHour?.['13'] ?? []; const at21 = cache.statistics.specialByHour?.['21'] ?? [];
  return <main className={dark ? 'dark' : ''}><header><div><h1>Lottto 5/35 — Phân tích số đặc biệt</h1><p>5 số xanh (01–35) + số đặc biệt cam (01–12). Dữ liệu lịch sử, không phải dự đoán.</p></div><button onClick={() => setDark(!dark)}>Đổi giao diện</button></header>
    <section className="cards"><article><small>Tổng kỳ quay</small><strong>{metadata.totalDraws}</strong></article><article><small>Kỳ mới nhất</small><strong>{metadata.latestDraw ?? '—'}</strong></article><article><small>Kiểm tra dữ liệu</small><strong className={payload.sourceStatus === 'live' ? 'live-status' : 'fallback-status'}>{payload.sourceStatus === 'live' ? 'Nguồn trực tuyến ✓' : 'Dữ liệu deploy'}</strong><small>{payload.checkedAt ? new Date(payload.checkedAt).toLocaleString('vi-VN') : 'Không thể kiểm tra trực tuyến'}</small></article></section>
    <section><h2>Tần suất và khoảng cách của số đặc biệt</h2><p className="muted">Đường xanh là số ngày kể từ lần xuất hiện gần nhất; cột cam là tổng số lần xuất hiện.</p><Chart options={specialChart(special)} /></section>
    <section><h2>Chu kỳ 01–12</h2><div className="table-wrap"><table><thead><tr><th>ĐB</th><th>Xuất hiện</th><th>Lần gần nhất</th><th>Trung bình lặp lại</th><th>Quá hạn / sớm</th><th>Khoảng cách (kỳ)</th></tr></thead><tbody>{special.map((item) => <tr key={item.number} className={item.number === selectedSpecial ? 'selected' : ''} onClick={() => setSelectedSpecial(item.number)}><td><span className="ball special">{numberLabel(item.number)}</span></td><td>{item.count}</td><td>{days(item.daysSinceLatest)}</td><td>{days(item.averageIntervalDays)}</td><td className={item.overdueDays > 0 ? 'overdue' : ''}>{item.overdueDays >= 0 ? '+' : ''}{item.overdueDays.toFixed(1)} ngày</td><td>{item.drawsSinceLatest} / TB {item.averageGapDraws.toFixed(1)}</td></tr>)}</tbody></table></div></section>
    <section className="two"><article><h2>Percentile khoảng cách hiện tại</h2><p className="muted">Càng gần 100% càng hiếm khi số ĐB đó vắng lâu như hiện tại.</p>{special.sort((a,b) => b.recurrencePercentile-a.recurrencePercentile).slice(0,3).map((item) => <p key={item.number}><span className="ball special">{numberLabel(item.number)}</span> <b>{item.recurrencePercentile.toFixed(0)}%</b> · vắng {days(item.daysSinceLatest)}</p>)}</article><article><h2>Backtest rolling Top-3 ĐB</h2><p>Đánh giá {backtest?.evaluated ?? 0} kỳ, chỉ dùng các kỳ quá khứ tại từng thời điểm.</p><strong>{((backtest?.top3HitRate ?? 0) * 100).toFixed(1)}%</strong><p className="muted">Tỷ lệ trúng Top-3: {backtest?.top3Hits ?? 0} kỳ. Mốc ngẫu nhiên: {((backtest?.baselineTop3Rate ?? .25) * 100).toFixed(1)}%.</p></article></section>
    <section className="two"><article><h2>Tách theo giờ quay</h2><div className="table-wrap"><table><thead><tr><th>ĐB</th><th>13h</th><th>21h</th></tr></thead><tbody>{special.map((item) => <tr key={item.number}><td><span className="ball special">{numberLabel(item.number)}</span></td><td>{at13.find((value) => value.number === item.number)?.count ?? 0} lần</td><td>{at21.find((value) => value.number === item.number)?.count ?? 0} lần</td></tr>)}</tbody></table></div></article><article><h2>Chuyển tiếp sau ĐB {numberLabel(selectedSpecial)}</h2><p className="muted">Các ĐB xuất hiện ở kỳ kế tiếp, sau khi ĐB {numberLabel(selectedSpecial)} xuất hiện.</p><div className="association-list">{transitions.slice(0,6).map((item) => <span className="association" key={item.number}><b>{numberLabel(item.number)}</b><br />{item.count} lần · {(item.rate*100).toFixed(1)}%</span>)}</div></article></section>
    <section><h2>ĐB quá hạn và các số xanh từng đi cùng</h2><p className="muted">Các card này ưu tiên số đặc biệt đang vượt chu kỳ trung bình. “Đi cùng” chỉ là tần suất lịch sử trong cùng kỳ quay, không phải khuyến nghị dự đoán.</p><div className="overdue-grid">{overdue.map((item) => { const related = cache.statistics.specialAssociations?.[String(item.number)] ?? []; return <article key={item.number} className={`overdue-card ${item.number === selectedSpecial ? 'active' : ''}`} onClick={() => setSelectedSpecial(item.number)}><div className="overdue-heading"><span className="ball special">{numberLabel(item.number)}</span><div><strong>+{item.overdueDays.toFixed(1)} ngày</strong><small>TB lặp lại {days(item.averageIntervalDays)}</small></div></div><p className="muted">Top số xanh từng đi cùng ({item.count} kỳ có ĐB {numberLabel(item.number)})</p><div className="association-list">{related.slice(0, 5).map((relation) => <span key={relation.number} className="association"><b>{numberLabel(relation.number)}</b><br />{relation.count} lần · {(relation.rate * 100).toFixed(1)}%</span>)}</div></article>; })}</div></section>
    <section className="two"><article><h2>ĐB {numberLabel(selectedSpecial)} và dãy 5 số xanh</h2><p className="muted">Chọn một hàng trong bảng hoặc một card quá hạn để đổi số đặc biệt.</p><p>ĐB {numberLabel(selectedSpecial)} đã xuất hiện {current?.count ?? 0} lần.</p></article><article><h2>Đọc chỉ số</h2><p><b>Quá hạn</b> = số ngày từ lần gần nhất trừ chu kỳ ngày trung bình.</p><p><b>Tỷ lệ đi cùng</b> = số lần số xanh xuất hiện cùng ĐB / tổng số kỳ của ĐB đó.</p></article></section>
    <section><h2>Số xanh thường đi cùng ĐB {numberLabel(selectedSpecial)}</h2><p className="muted">Số lần cùng xuất hiện trong một kỳ và tỷ lệ trên toàn bộ kỳ có số đặc biệt đã chọn.</p><Chart options={associationChart(selectedSpecial, associations)} /><div className="association-list">{associations.slice(0, 10).map((item) => <span key={item.number} className="association"><b>{numberLabel(item.number)}</b> {item.count} lần · {(item.rate * 100).toFixed(1)}%</span>)}</div></section>
  </main>;
}
