import type { EventRecord, EventRules, SpecialAssociation, SpecialMetric, Statistics } from '../core/domain';

const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
const combinations = (numbers: number[], size: number): string[] => size === 1 ? numbers.map(String) : numbers.flatMap((value, index) => combinations(numbers.slice(index + 1), size - 1).map((rest) => `${value},${rest}`));
const hour = (record: EventRecord) => record.timestamp.slice(11, 13);

export class StatisticsService {
  public constructor(private readonly rules: EventRules) {}
  private specialMetrics(records: readonly EventRecord[], now = new Date()): SpecialMetric[] {
    const count = new Map<number, number>(); const latest = new Map<number, { index: number; date: Date }>(); const gaps = new Map<number, number[]>(); const gapDays = new Map<number, number[]>();
    records.forEach((record, index) => { const date = new Date(record.timestamp); const previous = latest.get(record.specialNumber); count.set(record.specialNumber, (count.get(record.specialNumber) ?? 0) + 1); if (previous) { gaps.set(record.specialNumber, [...(gaps.get(record.specialNumber) ?? []), index - previous.index]); gapDays.set(record.specialNumber, [...(gapDays.get(record.specialNumber) ?? []), (date.getTime() - previous.date.getTime()) / 86400000]); } latest.set(record.specialNumber, { index, date }); });
    return Array.from({ length: this.rules.specialMax - this.rules.specialMin + 1 }, (_, offset) => { const number = offset + this.rules.specialMin; const intervals = gapDays.get(number) ?? []; const last = latest.get(number); const daysSinceLatest = last ? (now.getTime() - last.date.getTime()) / 86400000 : Number.POSITIVE_INFINITY; return { number, count: count.get(number) ?? 0, drawsSinceLatest: last ? records.length - 1 - last.index : records.length, daysSinceLatest, averageGapDraws: average(gaps.get(number) ?? []), averageIntervalDays: average(intervals), overdueDays: intervals.length ? daysSinceLatest - average(intervals) : 0, recurrencePercentile: intervals.length ? intervals.filter((gap) => gap <= daysSinceLatest).length / intervals.length * 100 : 0 }; });
  }
  private backtest(records: readonly EventRecord[]): Statistics['specialBacktest'] {
    const start = 60; let hits = 0; for (let index = start; index < records.length; index += 1) { const train = records.slice(Math.max(0, index - 120), index); const ranked = this.specialMetrics(train, new Date(records[index].timestamp)).sort((a, b) => (b.count + Math.max(0, b.overdueDays)) - (a.count + Math.max(0, a.overdueDays))).slice(0, 3); if (ranked.some((metric) => metric.number === records[index].specialNumber)) hits += 1; } const evaluated = Math.max(0, records.length - start); return { evaluated, top3Hits: hits, top3HitRate: evaluated ? hits / evaluated : 0, baselineTop3Rate: 3 / (this.rules.specialMax - this.rules.specialMin + 1) };
  }
  public build(records: readonly EventRecord[]): Statistics {
    const counts = new Map<number, number>(); const lastSeen = new Map<number, number>(); const gaps = new Map<number, number[]>(); const pairCounts = new Map<string, number>(); const associations = new Map<number, Map<number, number>>(); const transitions = new Map<number, Map<number, number>>(); const sums: number[] = []; const oddEven: Record<string, number> = {}; const highLow: Record<string, number> = {}; const rollingMeans: number[] = []; const midpoint = (this.rules.mainMax + this.rules.mainMin) / 2;
    records.forEach((record, index) => { const sum = record.mainNumbers.reduce((a, b) => a + b, 0); sums.push(sum); record.mainNumbers.forEach((number) => { counts.set(number, (counts.get(number) ?? 0) + 1); const last = lastSeen.get(number); if (last !== undefined) gaps.set(number, [...(gaps.get(number) ?? []), index - last]); lastSeen.set(number, index); }); const related = associations.get(record.specialNumber) ?? new Map<number, number>(); record.mainNumbers.forEach((number) => related.set(number, (related.get(number) ?? 0) + 1)); associations.set(record.specialNumber, related); if (index) { const from = records[index - 1].specialNumber; const next = transitions.get(from) ?? new Map<number, number>(); next.set(record.specialNumber, (next.get(record.specialNumber) ?? 0) + 1); transitions.set(from, next); } combinations(record.mainNumbers, 2).forEach((pair) => pairCounts.set(pair, (pairCounts.get(pair) ?? 0) + 1)); const odd = record.mainNumbers.filter((number) => number % 2).length; oddEven[`${odd} odd / ${record.mainNumbers.length - odd} even`] = (oddEven[`${odd} odd / ${record.mainNumbers.length - odd} even`] ?? 0) + 1; const high = record.mainNumbers.filter((number) => number > midpoint).length; highLow[`${high} high / ${record.mainNumbers.length - high} low`] = (highLow[`${high} high / ${record.mainNumbers.length - high} low`] ?? 0) + 1; rollingMeans.push(average(sums.slice(Math.max(0, index - 9), index + 1))); });
    const frequency = Array.from({ length: this.rules.mainMax - this.rules.mainMin + 1 }, (_, offset) => { const number = offset + this.rules.mainMin; return { number, count: counts.get(number) ?? 0, gap: records.length - 1 - (lastSeen.get(number) ?? -1), averageGap: average(gaps.get(number) ?? []) }; }); const specialFrequency = this.specialMetrics(records); const convert = (map: Map<number, number>, total: number): SpecialAssociation[] => [...map].map(([number, count]) => ({ number, count, rate: total ? count / total : 0 })).sort((a, b) => b.count - a.count || a.number - b.number); const specialAssociations = Object.fromEntries(specialFrequency.map((metric) => [String(metric.number), convert(associations.get(metric.number) ?? new Map(), metric.count)])); const specialTransitions = Object.fromEntries(specialFrequency.map((metric) => { const map = transitions.get(metric.number) ?? new Map(); return [String(metric.number), convert(map, [...map.values()].reduce((sum, count) => sum + count, 0))]; }));
    return { generatedAt: new Date().toISOString(), drawCount: records.length, frequency, specialFrequency, specialByHour: { '13': this.specialMetrics(records.filter((record) => hour(record) === '13')), '21': this.specialMetrics(records.filter((record) => hour(record) === '21')) }, specialAssociations, specialTransitions, specialBacktest: this.backtest(records), pairs: [...pairCounts].map(([key, count]) => ({ key, count })).sort((a, b) => b.count - a.count).slice(0, 50), distributions: { oddEven, highLow, sums }, rollingMeans };
  }
}
